- .idea/.gitignore
- .idea/bounswe2024group4.iml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- mobile/NBAForum/App.js
- mobile/NBAForum/constants/colors.js
- mobile/NBAForum/package-lock.json
- mobile/NBAForum/package.json
- mobile/NBAForum/pages/Login.js
- mobile/NBAForum/pages/SignUp.js
- mobile/NBAForum/pages/index.js
- Created a new directory named "pages" and added initial files: index.js, Login.js, SignUp.js, and colors.js. Made necessary additions to these files. Added basic functionality for SignUp in the SignUp.js file.
- Added modifications to the App.js file and included additional modules. Updated functionality as required.
> Added Pages directory and initial files. Made changes to App.js and added some modules.

- backend/nba_project/settings.py
- frontend/src/pages/SignIn.js
- frontend/src/pages/SignUp.js
Establishes the connection between the frontend and backend.
> Make frontend talk to backend

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Navbar.js
Navbar has been added to menu icon and profile icon but it has no functionality yet.Also,Changing mouse icon when it comes to logo and nba forum title.
> Implement enhanced navbar functionality

- backend/nba_app/views.py
- frontend/package-lock.json
- frontend/package.json
- frontend/src/index.js
- frontend/src/pages/Feed.js
- frontend/src/pages/SignIn.js
- frontend/src/pages/SignUp.js
> Migrate password validation and improve signup signin flows

- backend/nba_app/views.py
- backend/nba_project/settings.py
Searching the query among teams and players and return name and id
> Searching team and player

- backend/nba_app/views.py
Probably nothing will be added to team pages until the customer milestone
> lat and long added to team info

- frontend/src/components/Navbar.js
- frontend/src/components/searchbar.js
- frontend/src/pages/Player.js
- frontend/src/pages/Team.js
- frontend/src/routes/Router.js
Connects the data retrieved from Wikidata to their designated pages through the search flow.
Closes #166.
> Make the search / wikidata connection in frontend

- backend/nba_app/models.py
- backend/nba_app/urls.py
- backend/nba_app/views.py
1) Like and Bookmark models are added.
2) Now; follow, unfollow, and profile view endpoints takes username as input rather than user_id.
> some fixes and new endpoints about like and bookmark

- backend/nba_app/urls.py
- backend/nba_app/views.py
The endpoint for getting id's of bookmarked posts is added.
> bookmarked post ids

- frontend/src/components/Post.js
Adds profile picture to posts.
> Add profile picture to posts

- backend/nba_app/views.py
- mobile/NBAForum/pages/Feed.js
- mobile/NBAForum/pages/Post.js
Liking and commenting are implemented on mobile side.
> Mobile like comment

- backend/nba_app/views.py
Enhance search endpoint so that it returns more than one player and team if there is a match
> make search return more than one player or team

- backend/nba_app/views.py
Update team and player pages so that they make less api calls
> update teams and players

- backend/nba_app/views.py
team ok, player unfortunately reverse
> Finish team and player endpoints

- backend/nba_app/views.py
username and pp of the comment are added to the post details
> comment username and pp

- mobile/NBAForum/package.json
- mobile/NBAForum/pages/Post.js
icons are shown with another package,
comment details are displayed
> Mobile icon bug fix

- backend/nba_app/views.py
- mobile/NBAForum/navigator.js
- mobile/NBAForum/pages/Comment.js
- mobile/NBAForum/pages/OthersProfile.js
- mobile/NBAForum/pages/Post.js
- mobile/NBAForum/pages/index.js
now the users can follow each other and like each other's comments
> mobile comment like and follow

- frontend/src/pages/CreatePost.js
- frontend/src/pages/Feed.js
feed has been added and hyperlinks edited accordin to new backend's search results
closes #288
> feed last version has been added.

- frontend/src/components/Comment.js
- frontend/src/components/Post.js
- frontend/src/pages/PostFocus.js
- frontend/src/routes/Router.js
> Add comments and post specific page

- backend/nba_app/urls.py
- backend/nba_app/views.py
New endpoint which shows the users who have liked a specific post is added.
> get_users_like_post

- frontend/src/components/Post.js
- frontend/src/components/UserListInfoModal.js
- frontend/src/pages/Profile.js
- frontend/src/routes/Router.js
Adds modals to display who liked a post, and who follows you and who are you following in your own profile page.
> Add followers & followings & likers info

- mobile/NBAForum/package.json
- mobile/NBAForum/pages/CreatePost.js
- mobile/NBAForum/pages/Feed.js
last fixes: bookmarking works now
> refresh feed on focus

- frontend/fitness-diet-forum/package-lock.json
- frontend/fitness-diet-forum/package.json
- frontend/fitness-diet-forum/src/App.js
- frontend/fitness-diet-forum/src/css/index.css
- frontend/fitness-diet-forum/src/workInProgress.js
- frontend/fitness-diet-forum/tailwind.config.js
Tailwind css has been added to project,also a work in progress page added to show tailwind.
> Tailwind css has been added 

- frontend/fitness-diet-forum/package-lock.json
- frontend/fitness-diet-forum/package.json
- frontend/fitness-diet-forum/src/App.js
- frontend/fitness-diet-forum/src/components/Sidebar.js
- frontend/fitness-diet-forum/src/components/Topbar.js
sidebar and topbar has been added
> navbar- sidebar 

- frontend/fitness-diet-forum/.dockerignore
- frontend/fitness-diet-forum/Dockerfile
dockerfile for frontend has been created and tested.Frontend part successfully ran on docker
closes #362
> dockerfile has been created

- .env
- backend/Dockerfile
- docker-compose.yaml
DockerFile and DockerCompose set to working
> Can docker

- mobile/app/(tabs)/exercises.tsx
- mobile/app/exerciseProgramCreator.tsx
- mobile/app/exerciseSelector.tsx
- mobile/app/muscleGroupSelector.tsx
- mobile/constants/image_map.ts
- mobile/package-lock.json
- mobile/package.json
Finished except backend connection and the save button that will send the exercise program to backend.
> Finish exercise selection UI

- frontend/fitness-diet-forum/README.md
created frontend readme that contains the instructions to run the project locally
> create frontend readme

- backend/README.md
> Create README.md for backend

- frontend/fitness-diet-forum/package-lock.json
- frontend/fitness-diet-forum/package.json
- frontend/fitness-diet-forum/src/App.js
- frontend/fitness-diet-forum/src/components/Auth.js
- frontend/fitness-diet-forum/src/components/PrivateRoute.js
- frontend/fitness-diet-forum/src/pages/Login.js
- frontend/fitness-diet-forum/src/pages/Signup.js
login and signup pages are connected with backend . Private routing mechanism has been added. closes #435
> login and signup are connected with backend

- mobile/app/(tabs)/_layout.tsx
- mobile/app/(tabs)/leaderboard.tsx
Now, leaderboard tab on mobile can display workout ratings leaderboard, meal ratings leaderboard and combined leaderboard.
> Adding leaderboard screen to mobile

- frontend/fitness-diet-forum/src/components/DayProgram.js
- frontend/fitness-diet-forum/src/components/TodaysExercises.js
naming edited according the backend response data. now you will be able to see sets and reps too.
> connection finalized.

- frontend/fitness-diet-forum/src/components/ExerciseProgram.js
- frontend/fitness-diet-forum/src/pages/ExerciseProgramList.js
- frontend/fitness-diet-forum/src/pages/ProfilePage.js
exercise rating is implemented
> implement exercise program rating

- mobile/app/_layout.tsx
- mobile/app/login.tsx
- mobile/app/signup.tsx
Working sign-up and log in functionalities are added to mobile.
> Signup and login for mobile

- mobile/app/(tabs)/exercises.tsx
- mobile/app/exerciseSelector.tsx
- mobile/components/WorkoutProgram.tsx
Partially implements exercise app backend connection in mobile, still requires sending draft exercises to backend for saving.
> Connect backend to exercise display

- mobile/__tests__/home-test.tsx
- mobile/package-lock.json
- mobile/package.json
Adds unit test for the home page that redirects to signup and login pages.
> Add unit tests for home page to mobile

- frontend/fitness-diet-forum/src/__tests__/ExerciseProgram.test.js
- frontend/fitness-diet-forum/src/__tests__/LeaderBoard.test.js
implemented unit tests for leaderboard page loading and ExerciseProgram component
> implement unit tests

- mobile/__tests__/leaderboard-test.tsx
- mobile/app/(tabs)/leaderboard.tsx
Unit test added for leaderboard component that fetches the data from backend and displays accordingly.
> Add unit tests for leaderboard page to mobile

- mobile/app/(tabs)/_layout.tsx
- mobile/app/(tabs)/leaderboard.tsx
- mobile/app/(tabs)/profile.tsx
- mobile/app/EditProfileScreen.tsx
- mobile/app/login.tsx
- mobile/package-lock.json
- Profile page connected to backend to retrieve personal data.
- User profiles can be viewed from leaderboard after clicking the user's container.
> View profile from leaderboard

- .gitignore
- backend/.gitignore
- backend/profiles_app/views.py
view_profile now doesn't return only post id but also its content
> Fix mistake in view_profile

- mobile/app/(tabs)/profile.tsx
- mobile/components/WorkoutsScreen.tsx
Connected the profile's workout page to fetch data dynamically from the backend, enabling real-time updates and interactions.
> Integrate profile workout section with backend

- mobile/app/(tabs)/exercises.tsx
- mobile/app/exerciseProgramCreator.tsx
- mobile/app/exerciseSelector.tsx
- mobile/app/muscleGroupSelector.tsx
- mobile/components/WorkoutEdit.tsx
- mobile/components/WorkoutProgram.tsx
- mobile/constants/image_map.ts
- mobile/constants/types.ts
- Workout program creation UI connected backend.
- Some bugs occuring while displaying muscle images or exercise instructions are fixed
> Create workout programs on mobile

- backend/profiles_app/views.py
- frontend/fitness-diet-forum/src/components/CreatePostModal.js
- frontend/fitness-diet-forum/src/components/ExerciseProgram.js
- frontend/fitness-diet-forum/src/components/Post.js
- frontend/fitness-diet-forum/src/components/WeekProgram.js
- frontend/fitness-diet-forum/src/pages/ExerciseProgramList.js
- frontend/fitness-diet-forum/src/pages/Exercises.js
- frontend/fitness-diet-forum/src/pages/LeaderBoard.js
- frontend/fitness-diet-forum/src/pages/ProfilePage.js
all the authorization tokens are updated in frontend according to the new system
> frontend auth update

- backend/profiles_app/views.py
- frontend/fitness-diet-forum/src/components/EditProfileForm.js
- frontend/fitness-diet-forum/src/pages/Login.js
- frontend/fitness-diet-forum/src/pages/ProfilePage.js
- the way new profile picture is retrieved from frontend in the endpoint is changed
- edit profile is implemented in frontend
> edit profile is implemented in frontend

- mobile/app/(tabs)/exercises.tsx
- mobile/app/(tabs)/leaderboard.tsx
- mobile/app/exerciseProgramCreator.tsx
- mobile/app/exerciseSelector.tsx
- mobile/app/login.tsx
- mobile/app/signup.tsx
Mobile is updated according to backend authentication changes.
> Mobile auth update

- frontend/fitness-diet-forum/package-lock.json
- frontend/fitness-diet-forum/package.json
- frontend/fitness-diet-forum/src/App.test.js
- frontend/fitness-diet-forum/src/__tests__/CreatePostModal.test.js
- frontend/fitness-diet-forum/src/__tests__/EditProfileForm.test.js
- frontend/fitness-diet-forum/src/__tests__/ExerciseProgram.test.js
- frontend/fitness-diet-forum/src/__tests__/Feed.test.js
- frontend/fitness-diet-forum/src/__tests__/LeaderBoard.test.js
- frontend/fitness-diet-forum/src/__tests__/Post.test.js
- frontend/fitness-diet-forum/src/__tests__/ProfilePage.test.js
- frontend/fitness-diet-forum/src/components/Post.js
- frontend/fitness-diet-forum/src/components/WeightGraph.js
- frontend/fitness-diet-forum/src/pages/Feed.js
- frontend/fitness-diet-forum/src/pages/LeaderBoard.js
- frontend/fitness-diet-forum/src/pages/ProfilePage.js
**Unit Tests Implemented for:**
- CreatePostModal.js
- EditProfileForm.js
- ExerciseProgram.js
- Feed.js
- LeaderBoard.js
- Post.js
- ProfilePage.js
**Small Bug Fixes and Changes:**
- Changed weight graph color.
- Fixed toggling like bug (it wasn't working correctly when there is a network error)
- Made profile pictures visible inside the posts too
- Added created_at attribute to the posts
> Unit tests for frontend are implemented

- mobile/app/(tabs)/index.tsx
- mobile/app/createPostScreen.tsx
- mobile/components/CommentModal.tsx
- mobile/components/Post.tsx
- mobile/components/PostCreate.tsx
- mobile/components/WorkoutProgram.tsx
- mobile/constants/types.ts
Adds bookmarking, a comments modal, and likes to the posts in mobile app. Also improves the styling for the post component.
> Add post actions to mobile

- frontend/fitness-diet-forum/src/components/MuscleGroups.js
- frontend/fitness-diet-forum/src/pages/ExerciseProgramList.js
- frontend/fitness-diet-forum/src/pages/Exercises.js
super_members now have the privilege of creating an exercise
> implement exercise creation of super_members

- mobile/app/(tabs)/exercises.tsx
- mobile/app/exerciseProgramCreator.tsx
- mobile/components/Post.tsx
- mobile/components/WorkoutEdit.tsx
- mobile/components/WorkoutProgram.tsx
- mobile/constants/types.ts
Fixes workout save bug in mobile, also does styling updates to workout program.
> Fix workout save bug

- mobile/components/Post.tsx
- mobile/components/WorkoutProgram.tsx
Adds rating and bookmarking workout programs in mobile app.
Closes #602 #596
> Add bookmarking and rating workout programs

- mobile/app/(tabs)/leaderboard.tsx
- mobile/app/(tabs)/profile.tsx
- mobile/components/BookmarksScreen.tsx
Implemented the BookmarkScreen component to display bookmarked posts.
> Added BookmarkScreen to display bookmarked posts

- mobile/app/(tabs)/profile.tsx
- mobile/app/others-profile.tsx
- mobile/components/FeedScreen.tsx
This PR introduces the FeedScreen component, enabling the rendering of a list of user posts with associated user details.
> Implement FeedScreen Component for Rendering User Posts
